In [1]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint

pp = pprint.PrettyPrinter(indent=4)
sess = tf.Session()

In [2]:
### Simple Array
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


In [4]:
### 2D Array
t = np.array([[1., 2., 3.], 
              [4., 5., 6.], 
              [7., 8., 9.], 
              [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


In [6]:
### Shape, Rank, Axis
t = tf.constant([1,2,3,4])
tf.shape(t).eval(session=sess)

array([4], dtype=int32)

In [7]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval(session=sess)

array([2, 2], dtype=int32)

In [8]:
t = tf.constant([[[[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]],
                  [[13, 14, 15, 16], 
                   [17, 18, 19, 20], 
                   [21, 22, 23, 24]]]])
tf.shape(t).eval(session=sess)

array([1, 2, 3, 4], dtype=int32)

In [9]:
### Matmul VS multiply
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).eval(session=sess)

array([[ 12.]], dtype=float32)

In [10]:
(matrix1*matrix2).eval(session=sess)

array([[ 6.,  6.],
       [ 6.,  6.]], dtype=float32)

In [11]:
### Watch out broadcasting
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval(session=sess)

array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

In [12]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval(session=sess)

array([[ 5.,  5.]], dtype=float32)

In [14]:
### Random values for variable initializations
tf.random_normal([3]).eval(session=sess)

array([ 0.02152964, -1.46791613,  1.18191898], dtype=float32)

In [15]:
tf.random_uniform([2]).eval(session=sess)

array([ 0.70776451,  0.59957349], dtype=float32)

In [16]:
tf.random_uniform([2, 3]).eval(session=sess)

array([[ 0.69407558,  0.76553261,  0.50663781],
       [ 0.90043247,  0.03704309,  0.35918415]], dtype=float32)

In [17]:
### Reduce Mean/Sum
tf.reduce_mean([1, 2], axis=0).eval(session=sess)

1

In [19]:
x = [[1., 2.],
     [3., 4.]]

tf.reduce_mean(x).eval(session=sess)

2.5

In [20]:
tf.reduce_mean(x, axis=0).eval(session=sess)

array([ 2.,  3.], dtype=float32)

In [21]:
tf.reduce_mean(x, axis=1).eval(session=sess)

array([ 1.5,  3.5], dtype=float32)

In [22]:
tf.reduce_mean(x, axis=-1).eval(session=sess)

array([ 1.5,  3.5], dtype=float32)

In [23]:
tf.reduce_sum(x).eval(session=sess)

10.0

In [24]:
tf.reduce_sum(x, axis=0).eval(session=sess)

array([ 4.,  6.], dtype=float32)

In [25]:
tf.reduce_sum(x, axis=1).eval(session=sess)

array([ 3.,  7.], dtype=float32)

In [26]:
tf.reduce_sum(x, axis=-1).eval(session=sess)

array([ 3.,  7.], dtype=float32)

In [27]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval(session=sess)

5.0

In [28]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval(session=sess)

array([1, 0, 0])

In [29]:
tf.argmax(x, axis=1).eval(session=sess)

array([2, 0])

In [30]:
tf.argmax(x, axis=-1).eval(session=sess)

array([2, 0])

In [31]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [33]:
tf.reshape(t, shape=[-1, 3]).eval(session=sess)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
tf.reshape(t, shape=[-1, 1, 3]).eval(session=sess)

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [35]:
tf.squeeze([[0], [1], [2]]).eval(session=sess)

array([0, 1, 2], dtype=int32)

In [36]:
tf.expand_dims([0, 1, 2], 1).eval(session=sess)

array([[0],
       [1],
       [2]], dtype=int32)

In [37]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval(session=sess)

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [38]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval(session=sess)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

In [39]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval(session=sess)

array([1, 2, 3, 4], dtype=int32)

In [40]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval(session=sess)

array([1, 0, 1, 0], dtype=int32)

In [41]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval(session=sess)

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [42]:
tf.stack([x, y, z], axis=1).eval(session=sess)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [43]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval(session=sess)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [44]:
tf.zeros_like(x).eval(session=sess)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [45]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [46]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


In [49]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [50]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [51]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [52]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [54]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
