In [1]:
import tensorflow as tf
import numpy as np
import pprint
# The amount of indentation added for each recursive level is specified by indent
pp = pprint.PrettyPrinter(indent=4)
# A TensorFlow Session for use in interactive contexts, such as a shell.
sess = tf.InteractiveSession()

In [2]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [3]:
with tf.variable_scope('one_cell') as scope:
    # One cell RNN input_dim (4) -> output_dim (2)
    hidden_size = 2
    cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)
    print(cell.output_size, cell.state_size)
    
    x_data = np.array([[h]], dtype=np.float32)  # x_data = [[[1, 0, 0, 0]]]
    pp.pprint(x_data)
    outputs, _states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

2 LSTMStateTuple(c=2, h=2)
array([[[ 1.,  0.,  0.,  0.]]], dtype=float32)


array([[[-0.00986737,  0.08827952]]], dtype=float32)


In [5]:
with tf.variable_scope('two_Sequance') as scope:
    # One cell RNN input_dim (4) -> output_dim (2). sequence: 5
    hidden_size = 2
    cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size)
    x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
    print(x_data.shape)
    pp.pprint(x_data)
    outputs, states = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

(1, 5, 4)
array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]]], dtype=float32)


array([[[-0.17342447, -0.11040392],
        [-0.14710532, -0.0880381 ],
        [-0.04727915,  0.00759707],
        [ 0.03275947,  0.10922783],
        [-0.03082429,  0.16426583]]], dtype=float32)


In [7]:
with tf.variable_scope('three_batches') as scope:
    # One cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
    # 3 batches 'hello', 'eolll', 'lleel'
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l],
                       [l, l, e, e, l]], dtype=np.float32)
    pp.pprint(x_data)
    
    hidden_size = 2
    cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_size, state_is_tuple=True)
    outputs, _states = tf.nn.dynamic_rnn(
        cell, x_data, dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)


array([[[ 0.11832543,  0.06595117],
        [ 0.24702589,  0.06833063],
        [ 0.00737679,  0.10611526],
        [-0.12257072,  0.12333389],
        [-0.04216179,  0.17945966]],

       [[ 0.09426524,  0.03051019],
        [ 0.11478826,  0.10977624],
        [-0.04812833,  0.11253216],
        [-0.15550891,  0.12797628],
        [-0.21438219,  0.13898197]],

       [[-0.12731183,  0.04452415],
        [-0.19899371,  0.07781581],
        [-0.13731883,  0.07561703],
        [-0.0184495 ,  0.08043462],
        [-0.13548696,  0.11502461]]], dtype=float32)


In [3]:
with tf.variable_scope('4_batches_dynamic_length') as scope:
    # One cell RNN input_dim(4) -> output_dim(5). sequence: 5, batch: 3
    # 3 batches 'hello', 'eolll', lleel'
    x_data = np.array([[h, e, l, l, o],
                       [e, o, l, l, l],
                       [l, l, e, e, l]], dtype=np.float32)
    pp.pprint(x_data)
    
    hidden_size = 2
    cell = tf.contrib.rnn.BasicLSTMCell(
        num_units=hidden_size, state_is_tuple=True)
    outputs, _states = tf.nn.dynamic_rnn(
        cell, x_data, sequence_length=[5, 3, 4], dtype=tf.float32)
    sess.run(tf.global_variables_initializer())
    pp.pprint(outputs.eval())

array([[[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  1.]],

       [[ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.]],

       [[ 0.,  0.,  1.,  0.],
        [ 0.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.]]], dtype=float32)


array([[[ 0.0721793 ,  0.13097814],
        [-0.11776391,  0.03797518],
        [-0.00934804,  0.06844412],
        [ 0.06009306,  0.08930077],
        [ 0.19321541,  0.12593642]],

       [[-0.13883205, -0.03516557],
        [ 0.07524952,  0.01027522],
        [ 0.11228669,  0.03315873],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ]],

       [[ 0.07288288,  0.0319352 ],
        [ 0.11952929,  0.05511245],
        [-0.07736782,  0.00389756],
        [-0.17417836, -0.02751253],
        [ 0.        ,  0.        ]]], dtype=float32)
